name: "Intelbras MQTT Bridge"
version: "3.0.0"
slug: "intelbras_bridge"
description: "Full-featured bridge for Intelbras alarm panels (AMT-8000 and similar) via MQTT."
url: "https://github.com/elvis-epx/alarme-intelbras"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
homeassistant_api: true
startup: "application"
boot: "auto"
init: false
host_network: true
services:
  - "mqtt:want"
ports:
  "9009/tcp": null
ports_description:
  "9009/tcp": "Port for the alarm panel to send events to this Add-on"
options:
  alarm_ip: "192.168.1.7"
  alarm_port: 9009
  alarm_password: 781152
  password_length: 6
  polling_interval_minutes: 5
schema:
  alarm_ip: str
  alarm_port: port
  alarm_password: password(4,6)
  password_length: int(4,6)
  polling_interval_minutes: int(0,1440)
    - str
  zone_types:
    - str
