name: "Intelbras MQTT Bridge"
version: "3.0.0"
slug: "intelbras_bridge"
description: "Full-featured bridge for Intelbras alarm panels (AMT-8000 and similar) via MQTT."
url: "https://github.com/elvis-epx/alarme-intelbras" # Cuando crees tu fork, reemplaza esto con tu URL
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
homeassistant_api: true
startup: "application"
boot: "auto"
init: false
host_network: true
services:
  - "mqtt:want"
ports:
  "9009/tcp": null
ports_description:
  "9009/tcp": "Port for the alarm panel to send events to this Add-on"
options:
  mqtt_broker: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: "mqtt"
  mqtt_password: "W00d5tock99."
  alarm_ip: 192.168.1.7
  alarm_port: 9009
  alarm_password: 781152
  password_length: 6
  polling_interval_minutes: 5
  zone_count: 8
  zone_names:
    - "Zona 1"
    - "Zona 2"
    - "Zona 3"
    - "Zona 4"
    - "Zona 5"
    - "Zona 6"
    - "Zona 7"
    - "Zona 8"
  zone_types:
    - "opening"
    - "opening"
    - "motion"
    - "motion"
    - "smoke"
    - "problem"
    - "problem"
    - "safety"
schema:
  mqtt_broker: str
  mqtt_port: int(1,65535)
  mqtt_user: str
  mqtt_password: password
  alarm_ip: str
  alarm_port: port
  alarm_password: int(1000,999999)
  password_length: int(4,8)
  polling_interval_minutes: int(0,1440)
  zone_count: int(1,64)
  zone_names: list(str)
  zone_types: list(str)
log_level: info
schema:
  log_level: str

